import { Quest } from '../services/firestoreService';

export const QUEST_DEFINITIONS: Quest[] = [
  // Main Quests
  {
    id: 'main-quest-1',
    name: 'Timber Hearth',
    description: 'Explore Timber Hearth and take a quiz.',
    category: 'Exploration',
    theme: 'Main Story',
    type: 'main',
    conditions: [{ stat: 'totalQuizzes', operator: '>=', value: 1 }],
    reward: 100,
  },
  {
    id: 'main-quest-2',
    name: 'Ash Twin',
    description: 'Explore Ash Twin and take a quiz.',
    category: 'Exploration',
    theme: 'Main Story',
    type: 'main',
    conditions: [{ stat: 'totalQuizzes', operator: '>=', value: 1 }],
    reward: 100,
  },
  {
    id: 'main-quest-3',
    name: 'Brittle Hollow',
    description: 'Explore Brittle Hollow and take a quiz.',
    category: 'Exploration',
    theme: 'Main Story',
    type: 'main',
    conditions: [{ stat: 'totalQuizzes', operator: '>=', value: 1 }],
    reward: 100,
  },
  {
    id: 'main-quest-4',
    name: 'Ember Twin',
    description: 'Explore Ember Twin and take a quiz.',
    category: 'Exploration',
    theme: 'Main Story',
    type: 'main',
    conditions: [{ stat: 'totalQuizzes', operator: '>=', value: 1 }],
    reward: 100,
  },
  {
    id: 'main-quest-5',
    name: 'Giants Deep',
    description: 'Explore Giants Deep and take a quiz.',
    category: 'Exploration',
    theme: 'Main Story',
    type: 'main',
    conditions: [{ stat: 'totalQuizzes', operator: '>=', value: 1 }],
    reward: 100,
  },
  {
    id: 'main-quest-6',
    name: 'Dark Bramble',
    description: 'Explore Dark Bramble and take a quiz.',
    category: 'Exploration',
    theme: 'Main Story',
    type: 'main',
    conditions: [{ stat: 'totalQuizzes', operator: '>=', value: 1 }],
    reward: 100,
  },
  {
    id: 'main-quest-7',
    name: 'Quantum Moon',
    description: 'Explore the Quantum Moon and take a quiz.',
    category: 'Exploration',
    theme: 'Main Story',
    type: 'main',
    conditions: [{ stat: 'totalQuizzes', operator: '>=', value: 1 }],
    reward: 100,
  },
  // Daily Quests
  {
    id: 'daily-quiz-1',
    name: 'Daily Dose of Trivia',
    description: 'Complete one quiz.',
    category: 'General',
    theme: 'Daily Challenge',
    type: 'daily',
    conditions: [{ stat: 'totalQuizzes', operator: '>=', value: 1 }],
    reward: 20,
  },
  {
    id: 'daily-correct-5',
    name: 'Quick Learner',
    description: 'Answer 5 questions correctly.',
    category: 'General',
    theme: 'Daily Challenge',
    type: 'daily',
    conditions: [{ stat: 'totalScore', operator: '>=', value: 50 }], // Assuming 10 points per correct answer
    reward: 30,
  },

  // Weekly Quests
  {
    id: 'weekly-streak-3',
    name: 'Consistent Challenger',
    description: 'Maintain a 3-day streak.',
    category: 'Consistency',
    theme: 'Weekly Goals',
    type: 'weekly',
    conditions: [{ stat: 'longestStreak', operator: '>=', value: 3 }],
    reward: 100,
  },
  {
    id: 'weekly-score-500',
    name: 'Weekly High Score',
    description: 'Score 500 points in a week.',
    category: 'Performance',
    theme: 'Weekly Goals',
    type: 'weekly',
    conditions: [{ stat: 'totalScore', operator: '>=', value: 500 }],
    reward: 150,
  },

  // Monthly Quests
  {
    id: 'monthly-master',
    name: 'Trivia Master',
    description: 'Answer 100 questions correctly in a month.',
    category: 'Mastery',
    theme: 'Monthly Milestones',
    type: 'monthly',
    conditions: [{ stat: 'totalScore', operator: '>=', value: 1000 }],
    reward: 500,
  },
];
